In [ ]:
#Matrix
#Matrix Operation
#Transpose of Matrix
#Detreminant of Matrix
#Inverse of matrix
#Rank of matrix
#Matix Decomposition
#eigen Values and Eigen Vectors

Create a Matrix of size 3*3 (3 rows and 3 colums).Perform the following Operation:

A)Add 50 to your matrix

B)Subtract 20 in your matrix

C)Multiply 3 in your matrix

D)Divide your matrix by 4.

In [ ]:
import numpy as np

In [ ]:
M1=np.random.randint(10,50,size=(3,3))

In [ ]:
M1

array([[33, 30, 24],
       [38, 41, 24],
       [13, 41, 40]])

In [ ]:
#Scalar Operations
M1+50

array([[83, 80, 74],
       [88, 91, 74],
       [63, 91, 90]])

In [ ]:
M1-20

array([[13, 10,  4],
       [18, 21,  4],
       [-7, 21, 20]])

In [ ]:
M1*3

array([[ 99,  90,  72],
       [114, 123,  72],
       [ 39, 123, 120]])

In [ ]:
M1/4

array([[ 8.25,  7.5 ,  6.  ],
       [ 9.5 , 10.25,  6.  ],
       [ 3.25, 10.25, 10.  ]])

Create two 3*3 matrices and then perform additon,subtraction,multiplication and division between these two metrices.

In [ ]:
M1=np.array([[12,14,16],[10,8,6],[3,4,5]])
M2=np.array([[1,4,6],[20,18,16],[13,14,15]])
print(M1)

[[12 14 16]
 [10  8  6]
 [ 3  4  5]]


In [ ]:
print(M2)

[[ 1  4  6]
 [20 18 16]
 [13 14 15]]


In [ ]:
#Matrix Operation
M1+M2

array([[13, 18, 22],
       [30, 26, 22],
       [16, 18, 20]])

In [ ]:
M1-M2

array([[ 11,  10,  10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [ ]:
M1*M2

array([[ 12,  56,  96],
       [200, 144,  96],
       [ 39,  56,  75]])

In [ ]:
M1/M2

array([[12.        ,  3.5       ,  2.66666667],
       [ 0.5       ,  0.44444444,  0.375     ],
       [ 0.23076923,  0.28571429,  0.33333333]])

Perform dot product between two matrix of size(2*2).

In [ ]:
M1=np.array([[12,14],[10,8]])
M2=np.array([[1,4],[20,16]])

print(M1)

print(M2)

dot_prod=np.dot(M1,M2)
print(dot_prod)

[[12 14]
 [10  8]]
[[ 1  4]
 [20 16]]
[[292 272]
 [170 168]]


**Note**:Columns of first matrix must be equal to rows of second matrix

**Tanspose of the Metrix**


Create a 3*3 Matrix and perform its Tanspose.

In [ ]:
M1=np.random.randint(10,50,size=(3,3))

In [ ]:
M1

array([[30, 12, 25],
       [42, 14, 11],
       [40, 48, 48]])

In [ ]:
trans_M1=M1.T
trans_M1

array([[30, 42, 40],
       [12, 14, 48],
       [25, 11, 48]])

**Property1: Tanspose of a Transposed matrix is the original Matrix**

In [ ]:
trans_M1.T

array([[30, 12, 25],
       [42, 14, 11],
       [40, 48, 48]])

**Property2:(Additive Property):(A+B).T=A.T+B.T**

In [ ]:
A=np.array([[4,5],[3,8],[20,30]])
B=np.array([[12,14],[45,5],[9,8]])

x=(A+B).T
print(x)

y=A.T+B.T
print(y)

if np.array_equal(x,y):
  print("Additive property is True")

else:
  print("Additive Property id False")

[[16 48 29]
 [19 13 38]]
[[16 48 29]
 [19 13 38]]
Additive property is True


**Property3:Multiplication Property of the transpose:(AxB).T=B.TxA.T**

In [ ]:
A=np.array([[4,3,1],[8,9,6],[7,5,7]])
B= np.array([[1,2,7],[3,4,5],[5,6,9]])

x=np.dot(A,B).T
print(x)
print()
y=B.T.dot(A.T)
print(y)

if np.array_equal(x,y):
  print("Multiplicative property is True")

else:
  print("Multiplicative Property id False")

[[ 18  65  57]
 [ 26  88  76]
 [ 52 155 137]]

[[ 18  65  57]
 [ 26  88  76]
 [ 52 155 137]]
Multiplicative property is True


**Determinant**

To find the determinant the matrix should be square(rows and columns be shape).

If det!=0,Matrix is Invertible

If det=0,Matrix is Not Invertible.

Create a 3*3 matrix and find the determinant of the matrix.

In [ ]:
M1=np.random.randint(10,50,size=(3,3))
M1

array([[42, 31, 28],
       [26, 44, 47],
       [38, 39, 11]])

In [ ]:
#to find detreminant
np.linalg.det(M1)

np.float64(-28582.000000000004)

**Inverse**

In [ ]:
#to find the inverse
M1_inv=np.linalg.inv(M1)

In [ ]:
M1_inv

array([[ 0.04719754, -0.02627528, -0.00787209],
       [-0.05248058,  0.02106221,  0.04359387],
       [ 0.02302148,  0.01609405, -0.03645651]])

In [ ]:
np.round(M1 @ M1_inv,decimals=4)

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

**Rank**

The number of independent rows or colums in matrix.

In [ ]:
A=np.array([[1,2],[2,4]])
np.linalg.matrix_rank(A)

np.int64(1)

In [ ]:
A=np.array([[1,2],[5,6]])
np.linalg.matrix_rank(A)

np.int64(2)

**Eigen Values and Eigen Vectors**

In [ ]:
A=np.array([[1,5],[3,2]])
eigVal,eigVec=np.linalg.eig(A)

In [ ]:
eigVal

array([-2.40512484,  5.40512484])

In [ ]:
eigVec

array([[-0.82653237, -0.75033198],
       [ 0.56288918, -0.66106121]])